version: "3"
containers:
- name: workstation
  image: ubuntu
  memory: 1024
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  ports:
  - 80
gcp_projects:
- name: gcpproject
  services:
  - artifactregistry.googleapis.com
  - cloudresourcemanager.googleapis.com
  roles: []
